[package]
name = "podcasts"
version = "0.1.0"
authors = ["Blake Winton <bwinton@latte.ca>"]

[dependencies]
chrono = "0.4.6"
failure = "0.1.3"
failure_derive = "0.1.3"
lazy_static = "1.1.0"
mp3-duration = "0.1.3"
rayon = "1.0.2"
regex = "1.0.5"
reqwest = "0.9.4"
rss = "1.6.0"
# rss = { path = "../rss" }
select = "0.4.2"
time = "0.1.40"
url = "1.7.1"
