[package]
name = "podcasts"
version = "0.1.0"
authors = ["Blake Winton <bwinton@latte.ca>"]

[dependencies]
chrono = "0.4"
failure = "0.1.1"
lazy_static = "0.2.2"
mp3-duration = "0.1.3"
rayon = "1.0.0"
regex = "0.2.6"
reqwest = "0.8.5"
# rss = "1.3.0"
rss = { path = "../rss" }
select = "0.4.2"
time = "0.1.37"
url = "1.7.0"
