[package]
name = "podcasts"
version = "0.1.0"
authors = ["Blake Winton <bwinton@latte.ca>"]

[dependencies]
chrono = "0.4.4"
failure = "0.1.1"
failure_derive = "0.1.1"
lazy_static = "1.0.2"
mp3-duration = "0.1.3"
rayon = "1.0.1"
regex = "1.0.1"
reqwest = "0.8.6"
rss = "1.5.0"
# rss = { path = "../rss" }
select = "0.4.2"
time = "0.1.40"
url = "1.7.1"
