[package]
name = "podcasts"
version = "0.1.0"
authors = ["Blake Winton <bwinton@latte.ca>"]

[dependencies]
chrono = "0.4.6"
failure = "0.1.5"
failure_derive = "0.1.5"
lazy_static = "1.3.0"
mp3-duration = "0.1.6"
rayon = "1.0.3"
regex = "1.1.6"
reqwest = "0.9.15"
rss = "1.7.0"
# rss = { path = "../rss" }
select = "0.4.2"
time = "0.1.42"
url = "1.7.2"